=== forpdi/plataforma-for/backend-java/src/main/resources/forpdi_structure_1.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	version="1.0">
	<xs:simpleType name="DataTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Currency" />
			<xs:enumeration value="DateField" />
			<xs:enumeration value="DateTimeField" />
			<xs:enumeration value="NumberField" />
			<xs:enumeration value="Percentage" />
			<xs:enumeration value="TextArea" />
			<xs:enumeration value="TextField" />
			<xs:enumeration value="BudgetField" />
			<xs:enumeration value="ActionPlanField" />
			<xs:enumeration value="ScheduleField" />
			<xs:enumeration value="SelectField" />
			<xs:enumeration value="TableField" />
			<xs:enumeration value="ResponsibleField" />
			<xs:enumeration value="AttachmentField" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ScheduleValueTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TextField" />
			<xs:enumeration value="NumberField" />
			<xs:enumeration value="DateField" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ScheduleValue">
		<xs:sequence>
			<xs:element name="valueLabel" type="xs:string" />
			<xs:element name="valueType" type="ScheduleValueTypes" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OptionLabel">
		<xs:sequence>
			<xs:element name="label" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Attribute">
		<xs:all>
			<xs:element name="label" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="type" type="DataTypes" />
			<xs:element name="optionsField">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="optionLabel" minOccurs="0" maxOccurs="unbounded"
							type="OptionLabel" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="scheduleOptions">
				<xs:complexType>
					<xs:all>
						<xs:element name="periodicity" type="xs:boolean"
							default="true" />
						<xs:element name="scheduleValues">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="scheduleValue" minOccurs="0"
										maxOccurs="unbounded" type="ScheduleValue" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:all>
				</xs:complexType>
			</xs:element>
		</xs:all>
		<xs:attribute name="required" type="xs:boolean" default="false" />
		<xs:attribute name="visibleInTables" type="xs:boolean" default="false" />
		<xs:attribute name="finishDate" type="xs:boolean" default="false" />
		<xs:attribute name="expectedField" type="xs:boolean" default="false" />
		<xs:attribute name="justificationField" type="xs:boolean" default="false" />
		<xs:attribute name="minimumField" type="xs:boolean" default="false" />
		<xs:attribute name="maximumField" type="xs:boolean" default="false" />
		<xs:attribute name="reachedField" type="xs:boolean" default="false" />
		<xs:attribute name="polarityField" type="xs:boolean" default="false" />
		<xs:attribute name="formatField" type="xs:boolean" default="false" />
		<xs:attribute name="periodicityField" type="xs:boolean" default="false" />
		<xs:attribute name="beginField" type="xs:boolean" default="false" />
		<xs:attribute name="endField" type="xs:boolean" default="false" />
		<xs:attribute name="bscField" type="xs:boolean" default="false" />
	</xs:complexType>

	<xs:element name="level" type="StructureLevel" />

	<xs:complexType name="StructureLevel">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="description" type="xs:string" />
			<xs:element name="indicator" type="xs:boolean" default="false" />
			<xs:element name="goal" type="xs:boolean" default="false" />
			<xs:element name="objective" type="xs:boolean" default="false" />
			<xs:element name="attributes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="attribute" minOccurs="1" maxOccurs="unbounded"
							type="Attribute" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="level" minOccurs="0" maxOccurs="1"
				type="StructureLevel" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="structure">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="structureName" type="xs:string" />
				<xs:element name="structureDescription" type="xs:string" />
				<xs:element name="structureLevels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="level" minOccurs="1" maxOccurs="unbounded"
								type="StructureLevel" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== forpdi/plataforma-for/backend-java/src/main/resources/forplad_2.0.xml
<?xml version="1.0" encoding="UTF-8" ?>
<structure xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="forpdi_structure_1.0.xsd">
	<structureName>ForPlad</structureName>
	<structureDescription>
		Estrutura de exemplo de um PDI de uma Universidade conforme o ForPlad.
	</structureDescription>
	<structureLevels>

		<level>
			<name>Eixo tem&#225;tico</name>
			<description>Quais os eixos tem&#225;ticos do seu PDI</description>
			<indicator>false</indicator>
			<goal>false</goal>
			<objective>false</objective>
			<attributes>
				<attribute required="true" visibleInTables="true">
					<type>ResponsibleField</type>
					<label>Respons&#225;vel</label>
					<description>Informe um respons&#225;vel</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
				<attribute required="true" visibleInTables="true">
					<type>TextArea</type>
					<label>Descri&#231;&#227;o</label>
					<description>Descri&#231;&#227;o do eixo tem&#225;tico</description>
					<optionsField></optionsField>
					<scheduleOptions>
						<periodicity></periodicity>
						<scheduleValues></scheduleValues>
					</scheduleOptions>
				</attribute>
			</attributes>
			<level>
				<name>Objetivo</name>
				<description>Objetivo para cada eixo tem&#225;tico</description>
				<indicator>false</indicator>
				<goal>false</goal>
				<objective>true</objective>
				<attributes>
					<attribute required="true" visibleInTables="true">
						<type>ResponsibleField</type>
						<label>Respons&#225;vel</label>
						<description>Informe um respons&#225;vel</description>
						<optionsField></optionsField>
						<scheduleOptions>
							<periodicity></periodicity>
							<scheduleValues></scheduleValues>
						</scheduleOptions>
					</attribute>
					<attribute required="true" visibleInTables="false">
						<type>TextArea</type>
						<label>Descri&#231;&#227;o</label>
						<description>Descri&#231;&#227;o do objetivo</description>
						<optionsField></optionsField>
						<scheduleOptions>
							<periodicity></periodicity>
							<scheduleValues></scheduleValues>
						</scheduleOptions>
					</attribute>
					<attribute required="true" visibleInTables="true"
						bscField="true">
						<type>SelectField</type>
						<label>Perspectiva do BSC</label>
						<description>Selecione uma perspectiva</description>
						<optionsField>
							<optionLabel>
								<label>Financeira</label>
							</optionLabel>
							<optionLabel>
								<label>Clientes</label>
							</optionLabel>
							<optionLabel>
								<label>Processos internos</label>
							</optionLabel>
							<optionLabel>
								<label>Aprendizado e crescimento</label>
							</optionLabel>
						</optionsField>
						<scheduleOptions>
							<periodicity></periodicity>
							<scheduleValues></scheduleValues>
						</scheduleOptions>
					</attribute>
					<attribute required="false" visibleInTables="false">
						<type>BudgetField</type>
						<label>Or&#231;amento</label>
						<description>Descri&#231;&#227;o do or&#231;amento</description>
						<optionsField></optionsField>
						<scheduleOptions>
							<periodicity></periodicity>
							<scheduleValues></scheduleValues>
						</scheduleOptions>
					</attribute>
				</attributes>
				<level>
					<name>Indicador</name>
					<description>Indicadores para cada objetivo</description>
					<indicator>true</indicator>
					<goal>false</goal>
					<objective>false</objective>
					<attributes>
						<attribute required="true" visibleInTables="true">
							<type>ResponsibleField</type>
							<label>Respons&#225;vel</label>
							<description>Informe um respons&#225;vel</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false">
							<type>TextArea</type>
							<label>Descri&#231;&#227;o</label>
							<description>Descri&#231;&#227;o do indicador</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false"
							periodicityField="true">
							<label>Periodicidade </label>
							<type>SelectField</type>
							<description>Escolha uma periodicidade</description>
							<optionsField>
								<optionLabel>
									<label>Anual</label>
								</optionLabel>
								<optionLabel>
									<label>Semestral</label>
								</optionLabel>
								<optionLabel>
									<label>Trimestral</label>
								</optionLabel>
								<optionLabel>
									<label>Bimestral</label>
								</optionLabel>
								<optionLabel>
									<label>Mensal</label>
								</optionLabel>
								<optionLabel>
									<label>Quinzenal</label>
								</optionLabel>
								<optionLabel>
									<label>Semanal</label>
								</optionLabel>
								<optionLabel>
									<label>Bienal</label>
								</optionLabel>
								<optionLabel>
									<label>Di&#225;ria</label>
								</optionLabel>
							</optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false"
							polarityField="true">
							<label>Polaridade</label>
							<type>SelectField</type>
							<description>Escolha uma polaridade </description>
							<optionsField>
								<optionLabel>
									<label>Maior-melhor</label>
								</optionLabel>
								<optionLabel>
									<label>Menor-melhor</label>
								</optionLabel>
							</optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false"
							formatField="true">
							<label>Formato</label>
							<type>SelectField</type>
							<description>Escolha um formato </description>
							<optionsField>
								<optionLabel>
									<label>Porcentagem</label>
								</optionLabel>
								<optionLabel>
									<label>Num&#233;rico</label>
								</optionLabel>
								<optionLabel>
									<label>Monet&#225;rio(R$)</label>
								</optionLabel>
								<optionLabel>
									<label>Horas</label>
								</optionLabel>
								<optionLabel>
									<label>Dias</label>
								</optionLabel>
								<optionLabel>
									<label>Meses</label>
								</optionLabel>
								<!-- <optionLabel> <label>Booleano (Sim ou N&#227;o)</label> </optionLabel> 
									<optionLabel> <label>Textual</label> </optionLabel> -->
							</optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="true"
							beginField="true">
							<type>DateField</type>
							<label>In&#237;cio</label>
							<description>Data de in&#237;cio</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="true"
							endField="true">
							<type>DateField</type>
							<label>Fim</label>
							<description>Data de fim</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false">
							<type>TextField</type>
							<label>Descri&#231;&#227;o do c&#225;lculo</label>
							<description>Descri&#231;&#227;o do C&#225;lculo</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="false" visibleInTables="false">
							<type>TextField</type>
							<label>&#211;rg&#227;o Respons&#225;vel</label>
							<description>&#211;rg&#227;o respons&#225;vel pelo indicador</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="true" visibleInTables="false">
							<type>ActionPlanField</type>
							<label>Plano de a&#231;&#227;o</label>
							<description>Plano de a&#231;&#227;o atual</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
						<attribute required="false" visibleInTables="false">
							<type>AttachmentField</type>
							<label>Anexar arquivos</label>
							<description>Anexe arquivos referente a esse indicador</description>
							<optionsField></optionsField>
							<scheduleOptions>
								<periodicity></periodicity>
								<scheduleValues></scheduleValues>
							</scheduleOptions>
						</attribute>
					</attributes>
					<level>
						<name>Meta</name>
						<description>Metas para cada indicador</description>
						<indicator>false</indicator>
						<goal>true</goal>
						<objective>false</objective>
						<attributes>
							<attribute required="true" visibleInTables="true">
								<type>ResponsibleField</type>
								<label>Respons&#225;vel</label>
								<description>Informe um respons&#225;vel</description>
								<optionsField></optionsField>
								<scheduleOptions>
									<periodicity></periodicity>
									<scheduleValues></scheduleValues>
								</scheduleOptions>
